### ISSUE TITLE
R for Mass Spectrometry

### ISSUE THREAD

**Issue by lgatto** [anuragraj/awesome-proteomics#1]
Would you consider a section on [R for Mass Spectrometry](https://www.rformassspectrometry.org/), a collection of quite a few R/Bioconductor packages for the analysis and interpretation of high throughput mass spectrometry assays, including proteomics (and metabolomics)?

I not as its own section (with say 3 - 4 packages and link for more), what would be a good option?

**Comment by anuragraj** [comment]
That's a great idea to include [R for Mass Spectrometry](https://www.rformassspectrometry.org/). Happy to accept your contributuion!
